---
services:

  sql-datagen:
    build:
      context: ../../connect/connect-cdc-xstream-oracle19-source/oracle-datagen/
    hostname: sql-datagen
    container_name: sql-datagen
    profiles:
    - sql_datagen
    volumes:
      - ../../connect/connect-cdc-xstream-oracle19-source/oracle-datagen//target/sql-datagen-1.0-SNAPSHOT-jar-with-dependencies.jar:/sql-datagen-1.0-SNAPSHOT-jar-with-dependencies.jar

  oracle:
    # You need to build this image first, following the instructions at
    # https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
    image: ${ORACLE_IMAGE}
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
      - "1532:1532"
    environment:
      ORACLE_PWD: Admin123

  connect:
    depends_on:
      - oracle
    volumes:
      - ../../connect/connect-cdc-xstream-oracle19-source/lib/instantclient/ojdbc8.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-xstream-cdc-source/lib/ojdbc8.jar
      - ../../connect/connect-cdc-xstream-oracle19-source/lib/instantclient/xstreams.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-xstream-cdc-source/lib/xstreams.jar
      - ../../connect/connect-cdc-xstream-oracle19-source/ssl/client/sqlnet.ora:/usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-xstream-cdc-source/sqlnet.ora
      - ../../connect/connect-cdc-xstream-oracle19-source/lib:/tmp/lib
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-xstream-cdc-source
      LD_LIBRARY_PATH: /tmp/lib/instantclient
      TNS_ADMIN: /usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-xstream-cdc-source
