---
version: '3.5'
services:


  nginx-proxy:
    image: reiz/nginx_proxy:latest
    hostname: nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-salesforce-cdc-source/nginx-proxy/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  mitmproxy:
    image: mitmproxy/mitmproxy
    hostname: mitmproxy
    container_name: mitmproxy
    command: mitmdump --flow-detail 4
    ports:
      - "8080:8080"
    volumes:
      - /Users/brettrandall/.mitmproxy:/home/mitmproxy/.mitmproxy

  sfdx-cli:
    image: vdesabou/sfdx-cli:latest # forked from salestrip/sfdx-cli to add plugin sfpowerkit
    hostname: sfdx-cli
    container_name: sfdx-cli
    command: "sleep infinity"

  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-salesforce
    dns: 0.0.0.0